name: Build, Test, Lint, and Deploy

on:
  push:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'v22.12.0'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run lint
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    needs: lint  # Ensures lint job runs first
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'v22.12.0'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run tests
        run: yarn test

  build:
    runs-on: ubuntu-latest
    needs: test  # Ensures test job runs first
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'v22.12.0'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build project
        run: yarn build

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensures build job runs first
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'v22.12.0'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Deploy to Railway
        uses: ./.github/actions/railway-deploy
        with:
          project_id: ${{ secrets.QA_PROJECT_ID }}
          environment: 'qa'
          railway_token: ${{ secrets.QA_RAILWAY_TOKEN }}
