name: Deploy to Railway

on:
  release:
    types:
      - created # Trigger on new semantic release
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  deploy-int:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Cache Node.js dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build project
        run: yarn build

      - name: Deploy to Railway
        uses: ./.github/actions/railway-deploy
        with:
          railway_token: ${{ secrets.INT_RAILWAY_TOKEN }}

  deploy-stage:
    runs-on: ubuntu-latest
    needs: [deploy-int]
    environment:
      name: staging
    if: ${{ github.event_name == 'release' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Await approval for Stage Deployment
        uses: actions/github-script@v4
        with:
          script: |
            const { owner, repo } = context.repo;
            await github.issues.createComment({
              owner,
              repo,
              issue_number: context.payload.release.id || 0,
              body: 'Please approve the deployment to staging.'
            });

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Cache Node.js dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build project
        run: yarn build

      - name: Deploy to Railway
        uses: ./.github/actions/railway-deploy
        with:
          railway_token: ${{ secrets.STAGE_RAILWAY_TOKEN }}

  deploy-prod:
    runs-on: ubuntu-latest
    needs: [deploy-stage]
    environment:
      name: production
    if: ${{ github.event_name == 'release' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Await approval for Production Deployment
        uses: actions/github-script@v4
        with:
          script: |
            const { owner, repo } = context.repo;
            await github.issues.createComment({
              owner,
              repo,
              issue_number: context.payload.release.id || 0,
              body: 'Please approve the deployment to production.'
            });

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Cache Node.js dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build project
        run: yarn build

      - name: Deploy to Railway
        uses: ./.github/actions/railway-deploy
        with:
          railway_token: ${{ secrets.PROD_RAILWAY_TOKEN }}
