name: Deploy to Railway

on:
  release:
    types:
      - published

jobs:
  deploy-int:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Cache Node.js dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build project
        run: yarn build

      - name: Deploy to Int Environment
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_INT_TOKEN }}
        run: |
          yarn global add railway
          railway up --detach

  deploy-stage:
    runs-on: ubuntu-latest
    needs: [deploy-int]
    environment:
      name: staging
    steps:
      - name: Await approval for Stage Deployment
        uses: actions/github-script@v4
        with:
          script: |
            const { context, github } = require('@actions/github');
            const { owner, repo } = context.repo;
            await github.issues.createComment({
              owner,
              repo,
              issue_number: context.payload.release.id,
              body: 'Please approve the deployment to staging.'
            });

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Cache Node.js dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build project
        run: yarn build

      - name: Deploy to Stage Environment
        id: deploy-stage
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_STAGE_TOKEN }}
        run: |
          yarn global add railway
          railway up --detach

  deploy-prod:
    runs-on: ubuntu-latest
    needs: [deploy-stage]
    environment:
      name: production
    steps:
      - name: Await approval for Production Deployment
        uses: actions/github-script@v4
        with:
          script: |
            const { context, github } = require('@actions/github');
            const { owner, repo } = context.repo;
            await github.issues.createComment({
              owner,
              repo,
              issue_number: context.payload.release.id,
              body: 'Please approve the deployment to production.'
            });

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Cache Node.js dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build project
        run: yarn build

      - name: Deploy to Production Environment
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_PROD_TOKEN }}
        run: |
          yarn global add railway
          railway up --detach
