name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.x'

      - name: Cache Node.js dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Print GitHub Token Scopes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "Checking GH_TOKEN scopes..."
          curl -s -H "Authorization: token $GH_TOKEN" https://api.github.com/ | jq '.'

      - name: Run release with debug logs
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.GH_TOKEN }}
          DEBUG: semantic-release:*
        run: |-
          unset GITHUB_TOKEN
          response=$(curl -s -H "Authorization: token $GH_TOKEN" https://api.github.com/user)

          # Parse username and email
          username=$(echo "$response" | jq -r '.login')
          email=$(curl -s -H "Authorization: token $GH_TOKEN" https://api.github.com/user/emails | jq -r '[.[] | select(.primary)][0].email')

          echo "GitHub Username: $username"
          echo "GitHub Email: $email"

          # Set git config
          git config --global user.name "$username"
          git config --global user.email "$email"
          echo $NPM_TOKEN | gh auth login --with-token
          gh auth status
          yarn release
